### PR TITLE
Add lint_staged to auto run eslint and prettier upon commit

### PR DESCRIPTION
**Pull request by bweis**
See title

### CODE REVIEW

**Comment by kddnewton** [comment]
@bweis needs a rebase

**Comment by kddnewton** [comment]
I think you probably need to call the husky binary directly from the node modules.

**Comment by bweis** [comment]
> I think you probably need to call the husky binary directly from the node modules.

Just hadn't added the yarn.lock.  Husky is setup as part of the npm prepare script.

**Comment by bweis** [comment]
Any chance of a 3.1.0 release today? @kddnewton

**Comment by kddnewton** [comment]
Already out!

**Pull request merged**
