### PR TITLE
 Added feature to order XML attributes by key alphabetically while prioritizing xmlns attributes

### PR DESCRIPTION
**Pull request by bweis**
I would love to discuss this feature.  While technically this does agains the ethos of prettier, it is super common for xml files.  Especially android xml layout files.

Open to a discussion and totally okay with closing this out if you disagree with the validity of its use case.

### CODE REVIEW

**Comment by kddnewton** [comment]
I am open to this feature being a part of this plugin, but would need a couple of things to change.

First, please prefix the attribute name with `xml`. Prettier can get confusing otherwise.

Second, at the moment you're sorting based on the printed output. That interface is not meant to be relied upon. If we decide to change the structure of our doc AST, we shouldn't have to go change this. Instead you should sort the attributes before you print them and rely on the XML AST.

If you can make those changes, I think we can consider merging this.

**Review by kddnewton — CHANGES_REQUESTED** [review]
Marking as "request changes".

**Comment by bweis** [comment]
I did attempt to do this at first actually. However it seems like the only interfaces for manipulating the "AST" were the from `xml-tools/parser` which gave us a CST.  Proving much more difficult to manipulate given it's Concrete nature.  Is there a built in util within the Prettier ecosystem for changing the AST before reaching the printer?

https://prettier.io/docs/en/plugins.html#developing-plugins

**Comment by kddnewton** [comment]
@bweis I don't think you would change the AST before it gets to the printer, you would do it within the printer. Right now you're calling:

```js
const attributes = path.map(print, "children", "attribute");

if (opts.sortAttributesByKey) {
  sortAttributesByKey(attributes);
}

parts.push(indent([line, join(separator, attributes)]));
```

but ideally you would be sorting before you print. You can do this in a lot of ways, but I would probably put the printed doc and the node itself into an object, as in:

```js
const attributes = path.map((attributePath) => ({
  node: attributePath.getValue(),
  printed: print(attributePath),
}), "children", "attribute");

if (opts.sortAttributesByKey) {
  attributes.sort(({ node: left }, { node: right }) => {
    // do the sorting here, based on the AST nodes
  });
}

parts.push(indent([line, join(separator, attributes.map(({ printed }) => printed))]));
```

**Comment by bweis** [comment]
Ack.  I misunderstood what you had meant.  Hopefully this looks good.

**Pull request merged**
