### PR TITLE
Update plugin.js: Add support for SVG

### PR DESCRIPTION
**Pull request by lifeiscontent**
Add support for SVG

### CODE REVIEW

**Comment by ericbf** [comment]
Can this be merged?

**Comment by lifeiscontent** [comment]
@ericbf I think its ready to go, just waiting to hear back from maintainers.

**Comment by kddeisz** [comment]
Merging this as part of https://github.com/prettier/plugin-xml/pull/39

**Comment by lifeiscontent** [comment]
@kddeisz will you be including my commit? I took my time to add support for it. I’d appreciate it if it was used.

**Comment by kddeisz** [comment]
Thanks for taking the time to make the contribution @lifeiscontent. I don't know how I would include your commit at this point as the support is already on master, but I'd be happy to merge any future contributions!

**Comment by lifeiscontent** [comment]
@kddeisz kind of a dick move, but ok

**Comment by lipis** [comment]
C'mon.. it wasn't intentional.

**Pull request closed without merging**
