### PR TITLE
fix: check for empty array

### LINKED ISSUE #158: TypeError: Cannot read property 'startLine' of undefined (v0.13.0)
I get the following error if i try to update to newest version

```

$ prettier "{**/*,*}.*" -u --list-different
--
1183 | [error] dir\file.xml: TypeError: Cannot read property 'startLine' of undefined
1184 | [error]     at Object.element (C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:336:34)
1185 | [error]     at Object.genericPrint [as print] (C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:412:30)
1186 | [error]     at callPluginPrintFunction (C:\drone\src\node_modules\prettier\index.js:14718:18)
1187 | [error]     at C:\drone\src\node_modules\prettier\index.js:14649:47
1188 | [error]     at Object.printComments (C:\drone\src\node_modules\prettier\index.js:14305:19)
1189 | [error]     at printGenerically (C:\drone\src\node_modules\prettier\index.js:14649:22)
1190 | [error]     at FastPath.call (C:\drone\src\node_modules\prettier\index.js:14441:20)
1191 | [error]     at C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:308:27
1192 | [error]     at Array.map (<anonymous>)
1193 | [error]     at Object.element (C:\drone\src\node_modules\@prettier\plugin-xml\src\printer.js:304:19)


```

*dir\file.xml*
```yml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<Event>
    <Process id="XXX.Notification">

    </Process>
    <!--<Process id="XXX.Notification.Tmpl" >
        <Condition>[v:NType] == 'Tmpl'</Condition>
    </Process>-->
</Event>

```

### PR DESCRIPTION
**Pull request by viceice**
Check for undefined

fixes #158

### CODE REVIEW

**Comment by kddeisz** [comment]
@viceice nice fix! If you can just run prettier on the printer.js file we should be good to go

**Comment by kddeisz** [comment]
This is out in v0.13.1

**Comment by viceice** [comment]
Wow, not expected that fast merge 😅

**Comment by nelson6e65** [comment]
Good job! Thanks for this bug fix! 😃

**Pull request merged**
